Feat/carrying capacity
mrc-ide/malariasimulation pull request #235
Opened 2023-04-25 15:47 UTC by pwinskill

Adds in functionality supply completely custom time varying and species specific carrying capacity vectors.

Functionality is implemented by pre-calculating the baseline carrying capacity at each time step for each species. This can then be overwriten or modified by the user specifying changes via 3 helper functions:

`set_larval_source_management()` For specific LSM intervention implementation
`set_rescaled_carrying_capacity()` For rescaling the carrying capacity as specified
`set_flexible_carrying_capacity()` For providing completely custom, user defined values.

Examples of use and implementation are included in the vignette `"Modifying the carrying capacity"`.

Other changes implemented:

- A catch in the aquatic model equations to stop the model returning an error if carrying capacty is 0. 
- Expose `calculate_carrying_capacity()` to the user to inform the use of `set_flexible_carrying_capacity()`

2023-04-27 13:14 UTC, giovannic requested changes
Ok!

Maintenance wise, I think it would be easier to have one `set_carrying_capacity` function. And we could demonstrate how to use it in the different ways in the vignette.

2023-04-27 13:14 UTC, giovannic commented on src/aquatic_mosquito_eqs.cpp
> +              model.rainfall_floor
indentation

2023-04-28 09:33 UTC, pwinskill commented
Thanks for the comments @giovannic 🙏. A few thoughts

**Regarding a single `set_carrying_cacpacity()` function** 
Agree this would be easier to maintain. This would be different to what we are currently doing with seasonality. As I see it currerntly the steps are:

1. User (effectively) sets the carrying capacity using `set_equilibrium()`
2. User specifies changes to carrying capacity using `model_seasonality = TRUE` etc
3. Modifications are then implemented within the model code.

It is that flow that I was trying to maintain with the proposed changes, addinging additional functions to specify unqiue and independent modifications to the carrying capacity.

**Regarding iterpolation**

So, unsurprisingly, it is possible to make the solver fall over with these changes. This occurs with large step-changes to the carrying capacity. I think the "flexibility" of a completly free `set_carrying_capacity()` function is the challenge here, as it will be impossible to tell _a priori_ if large step-like changes from the user are appropriate (for example implementing larval source management) or just clunky input.
When searching for parameterisations that would cause the solver to fail it was only when I put in what I would interpret as unreasonable parmeterisations (from a biological perspective) that issues would occur. In this case it seems completly reasonable to me that the model would(should) fall over. If that is the case then it would seem reasonable to me to inform the user about this via the vignette (and perhaps give a few more clues with the solver error message).

2023-05-30 11:07 UTC, giovannic approved these changes
Thank you so much for this!

2023-05-30 11:09 UTC, merged