Output render function
mrc-ide/malariasimulation pull request #276
Opened 2023-12-19 12:22 UTC by RJSheppard

I had a quick go at creating an age-grouping function. The function itself is pretty self-explanatory, but there are a few other changes that need a bit more explanation.

I had previously had non-functional code to separately render bite and relapse incidence by age. These would require the correct probabilities, subset for all bitten or all with hypnozoites respectively. Because the probabilities I had were the sum of both, having faffed around converting from probabilities to rates and back to probs, and subsetting, this seemed more hassle than it was worth, and I replaced it with total incidence by age, as found in falciparum. I matched the parameter list the reflect this (and rearranged slightly).

LS prophylaxis parameters have also been replaced with shape and scale parameters.

2023-12-19 13:33 UTC, giovannic requested changes
I like it!

Small suggestion on the defaults for `set_epi_outputs`

2023-12-19 13:33 UTC, giovannic commented on R/output_parameters.R
> +                            clinical_incidence = c(0, 1825),
```suggestion
                            clinical_incidence = NULL,
```

2023-12-19 13:33 UTC, giovannic commented on R/output_parameters.R
> +                            prevalence = c(730, 3650),
```suggestion
                            prevalence = NULL,
```

2023-12-20 09:22 UTC, pwinskill approved these changes
Like!
...and I learnt a new function: `formals()`

2023-12-21 11:00 UTC, merged