p.v sub-patent duration is immunity dependent.
mrc-ide/malariasimulation pull request #318
Opened 2024-07-03 14:20 UTC by RJSheppard

antiparasite immunity function shapes the duration of subpatent infection/rate of recovery from subpatent infection. These values are now assigned during the variable creation and calculation of recovery rates.

In previous iterations I have kept ID in the vivax model, where it acts as antiparasite immunity. For clarity of thought, I've now added IAA and IAM antiparasite immunities, including their decay, boosting, maternal immunity and reset at death.

We must also adjust the prevalence rendering, which for p.f is based on detectability immunity, and for p.v is explicit in the human states. p_detect_lm is also inappropriate for p.v as the lm_detection is explicit.

du, and ID parameters removed for vivax.

Tests are added for du rates and for prevalence rendering.

2024-07-08 11:25 UTC, pwinskill requested changes

2024-07-08 11:25 UTC, pwinskill commented on R/render.R
> +    } else {
You seem to mostly have `elseif (parameters$parasite == "vivax")` - is there a reason this is different?

2024-07-08 11:25 UTC, pwinskill commented on R/disease_progression.R
> +        )
Hard to parse like this, I think we can make it more efficient too (untested suggestion).
```suggestion
  # p.v subpatent recovery is immunity-dependent
  
  U_index <- variables$state$get_index_of("U")
  
  recovery_rates[U_index$to_vector()] <-
    1 / anti_parasite_immunity(
      min = parameters$dpcr_min,
      max = parameters$dpcr_max,
      a50 = parameters$apcr50,,
      k = parameters$kpcr,
      iaa = variables$iaa$get_values(index = U_index),
      iam =variables$iam$get_values(index = U_index)
    )
```

2024-07-08 11:25 UTC, pwinskill commented
/benchmark

2024-07-08 14:28 UTC, pwinskill commented
/benchmark

2024-08-01 10:51 UTC, pwinskill approved these changes

2024-10-10 11:55 UTC, giovannic commented
/benchmark

2024-10-10 13:27 UTC, giovannic approved these changes
Thank you!

2024-10-10 13:27 UTC, merged