Hotfix/pmc
mrc-ide/malariasimulation pull request #342
Opened 2024-12-13 14:02 UTC by RJSheppard

Fixing PMC timesteps bug

2024-12-18 15:01 UTC, pwinskill approved these changes
👍👍

2024-12-18 15:01 UTC, pwinskill commented on NEWS.md
> +* Fix PMC bug where timesteps to generate targetted individuals were not increasing
```suggestion
* Fix PMC bug where timesteps to generate targeted individuals were not increasing
```

2024-12-20 11:17 UTC, giovannic requested changes

2024-12-20 11:17 UTC, giovannic commented on DESCRIPTION
> +Version: 2.1.0
```suggestion
Version: 2.0.1
```

2024-12-20 11:17 UTC, giovannic commented on NEWS.md
> +# malariasimulation 2.1.0
```suggestion
# malariasimulation 2.0.1
```

2024-12-20 11:17 UTC, giovannic commented on DESCRIPTION
> +Version: 2.1.0
Changing to 2.0.1 to signify a bug fix with no breaking changes! [Semver](https://semver.org/spec/v2.0.0.html) for reference

2024-12-20 11:18 UTC, giovannic approved these changes

2024-12-27 12:06 UTC, merged